import Head from "next/head";
import { useSession } from "next-auth/react";
import App from "@/components/Navbar";
// import Map from "@/components/Map/Map";
import MapWithNoSSR from "@/components/Map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* <App style={{ scrollbars: "none" }} /> */}
        <MapWithNoSSR />
        {/* <Map /> */}
      </main>
    </>
  );
}
