import Head from "next/head";
import Button from "@/components/Button";
import Dashboard from "@/pages/Dashboard";
import Router from "next/router";
export default function Index() {
  const handleClick = async () => {
    Router.push("/dashboard/auth/login");
  };
  return (
    <>
      <Head>
        <title>Ghumakkad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button title="click and then check" onClick={handleClick} />
        <Dashboard />
      </main>
    </>
  );
}
