import Head from "next/head";
import { useSession } from "next-auth/react";
import App from "@/components/Navbar";
import Map from "@/components/Map/Map.jsx";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <App style={{ scrollbars: "none" }} /> */}
        <Map />
      </main>
    </>
  );
}
